name: Metrics
on:
        # Schedule updates every 6 hours
        schedule: [{cron: "* */6 * * *"}]

        workflow_dispatch:
        push: {branches: ["main", "master"]}
jobs:
        github-metrics:
                runs-on: ubuntu-latest
                permissions:
                  contents: write
                steps:
                        - name: Profile Metrics
                          uses: lowlighter/metrics@latest
                          with:
                                  token: ${{ secrets.METRICS_TOKEN }}
                                  repositories_skipped: Jokism/Jokism
                        - name: Organization Introduction
                          uses: lowlighter/metrics@latest
                          with:
                                  filename: metrics.plugin.introduction.svg
                                  repositories_skipped: Jokism/Jokism
                                  config_output: svg
                                  token: ${{ secrets.METRICS_TOKEN }}
                                  user: Jokism
                                  base: "header, repositories"
                                  plugin_lines: yes
                                  plugin_achievements: yes
                                  plugin_introduction: yes
                        - name: Languages
                          uses: lowlighter/metrics@latest
                          with:
                                  filename: metrics.plugin.languages.svg
                                  repositories_skipped: Jokism/Jokism
                                  token: ${{ secrets.METRICS_TOKEN }}
                                  plugin_languages: yes
                                  plugin_languages_indepth: yes
                                  commits_authoring: firstname lastname, username, username@users.noreply.github.com
                        - name: Compact Display
                          uses: lowlighter/metrics@latest
                          with:
                                  filename: metrics.plugin.achievements.compact.svg
                                  repositories_skipped: Jokism/Jokism
                                  token: ${{ secrets.METRICS_TOKEN }}
                                  base: ""
                                  plugin_achievements: yes
                                  plugin_achievements_display: compact

